// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-9Nhm5HVg0XbrE0iy-JIG2qnkjdlorbw',
    appId: '1:835884596247:web:0c123fe915a1d6746c3052',
    messagingSenderId: '835884596247',
    projectId: 'meow-food-butler',
    authDomain: 'meow-food-butler.firebaseapp.com',
    storageBucket: 'meow-food-butler.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXDPolTG55LW96mAAp-ldViMKJFCuZNbE',
    appId: '1:835884596247:android:02cce0780709e2106c3052',
    messagingSenderId: '835884596247',
    projectId: 'meow-food-butler',
    storageBucket: 'meow-food-butler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhbsQP7S9DvZTFqOS-NP-DgwlYduY24dM',
    appId: '1:835884596247:ios:df56ef81988ac9736c3052',
    messagingSenderId: '835884596247',
    projectId: 'meow-food-butler',
    storageBucket: 'meow-food-butler.firebasestorage.app',
    iosBundleId: 'com.example.meowFoodButler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhbsQP7S9DvZTFqOS-NP-DgwlYduY24dM',
    appId: '1:835884596247:ios:df56ef81988ac9736c3052',
    messagingSenderId: '835884596247',
    projectId: 'meow-food-butler',
    storageBucket: 'meow-food-butler.firebasestorage.app',
    iosBundleId: 'com.example.meowFoodButler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-9Nhm5HVg0XbrE0iy-JIG2qnkjdlorbw',
    appId: '1:835884596247:web:f17f4b603db61e986c3052',
    messagingSenderId: '835884596247',
    projectId: 'meow-food-butler',
    authDomain: 'meow-food-butler.firebaseapp.com',
    storageBucket: 'meow-food-butler.firebasestorage.app',
  );

}